# Generated by Django 5.1.4 on 2024-12-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_freelancer_verified_profile_is_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='freelancer_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_client',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_freelancer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
