# Generated by Django 5.1.4 on 2024-12-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
    ]
