# Generated by Django 5.1.4 on 2025-01-03 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_comment_deleted_at_comment_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
