# Generated by Django 5.1.4 on 2025-01-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_comment_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
