# Generated by Django 5.1.4 on 2025-01-04 07:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_remove_service_category_service_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
