# Generated by Django 5.1.4 on 2025-01-08 02:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_alter_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
