# Generated by Django 5.1.4 on 2025-01-13 10:14

import django.core.validators
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="訂單日期"),
                ),
                (
                    "total_price",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999999999),
                        ],
                        verbose_name="總金額",
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="訂單狀態",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("atm", "ATM"),
                            ("linepay", "Line Pay"),
                            ("googlepay", "Google Pay"),
                            ("barcode", "Barcode"),
                        ],
                        max_length=50,
                        verbose_name="付款方式",
                    ),
                ),
                (
                    "merchant_trade_no",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="商店訂單編號",
                    ),
                ),
                (
                    "selected_plan",
                    models.CharField(
                        blank=True,
                        choices=[("standard", "Standard"), ("premium", "Premium")],
                        max_length=20,
                        null=True,
                        verbose_name="選擇方案",
                    ),
                ),
                (
                    "client_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_as_client",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="客戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單",
                "verbose_name_plural": "訂單",
            },
        ),
    ]
