# Generated by Django 5.1.4 on 2024-12-30 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('services', '0004_service_rating_alter_service_premium_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '訂單', 'verbose_name_plural': '訂單'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_user_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_id',
        ),
        migrations.AddField(
            model_name='order',
            name='client_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_client', to=settings.AUTH_USER_MODEL, verbose_name='客戶'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services.service', verbose_name='服務'),
        ),
        migrations.AlterField(
            model_name='order',
            name='merchant_trade_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='商店訂單編號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='訂單日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('atm', 'ATM'), ('other', 'Other')], default='credit_card', max_length=50, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50, verbose_name='訂單狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總金額'),
        ),
    ]
