# Generated by Django 5.1.4 on 2025-01-01 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_options_remove_order_client_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("atm", "ATM"),
                    ("linepay", "Linepay"),
                ],
                max_length=50,
                verbose_name="付款方式",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999999999),
                ],
                verbose_name="總金額",
            ),
        ),
    ]
