# Generated by Django 5.1.4 on 2025-01-06 06:37

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_selected_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50, verbose_name='訂單狀態'),
        ),
    ]
