# Generated by Django 5.1.4 on 2025-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_selected_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='selected_plan',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20, null=True, verbose_name='選擇方案'),
        ),
    ]
